### ISSUE TITLE
Ошибка при обновлении, удалении или установке модуля

### ISSUE THREAD

**Issue by badigit** [directman66/majordomo-bletool#1]
Fatal error: Uncaught Error: Class 'bletool' not found in /var/www/html/modules/control_modules/control_modules.class.php(217) : eval()'d code:1 Stack trace: #0 /var/www/html/modules/control_modules/control_modules.class.php(217): eval() #1 /var/www/html/lib/module.class.php(311): control_modules->install() #2 /var/www/html/modules/control_modules/control_modules.class.php(19): module->checkInstalled() #3 /var/www/html/admin.php(25): control_modules->__construct() #4 {main} thrown in /var/www/html/modules/control_modules/control_modules.class.php(217) : eval()'d code on line 1

**Comment by directman66** [comment]
исправил, проверяйте
